### ISSUE TITLE
Is there any way to log this in console ?

### ISSUE THREAD

**Issue by akhi-ninja** [greenstick/interactor#2]
I was trying to log the events in console , its not logging anything 

and also there is one end point for event but when its sending events ? is there any another method to send the json , can is log the format in console ?

**Comment by greenstick** [comment]
Hi akhillgopinath,

Originally there was no way to access the full JSON payload as it was generated on submission to the server endpoint; this was a bit of an oversight on my part. I've updated Interactor to have a debug mode that is enabled by default – each time you click an element, it will log the full schema that will be sent to the server endpoint. I hope this helps. 

Pertaining to your last set of questions, I may need some clarification. It sounds like you're asking:

*  Is there one endpoint for the data? *No, you can customize the endpoint as needed through the 'endpoint' configuration argument.*
* When does Interactor send the interactions payload? *Right now, they're sent when the window.beforeunload event triggers. At some point I'll be updating the code to stream events using the Web Sockets API.*

Hope that helps, feel free to respond with any further questions / issues.

Thanks!

**Comment by akhi-ninja** [comment]
thanks @greenstick  , thanks for updating in a short time . Currently i dont have end point for this i can create one later , now i doing R&D on this . My requirement is to understand how to check function is really working when i hover a button in browser level . can you help me on that ?

**Comment by greenstick** [comment]
No sweat. To check its working, you can pass the argument `["mouseenter", "mouseleave"]` to the `interactionEvent` and/or `conversionEvent` properties (see README.md for an example of how to setup the config object). Note the default configuration will now log the `Interactor.session` object to console when you click a targeted element. Hope this helps!
