### ISSUE TITLE
example doesn't work

### ISSUE THREAD

**Issue by kimhjona** [greenstick/interactor#3]
No idea how to set this up. More thorough documentation and examples please. 

Looks promising though!

**Comment by greenstick** [comment]
Thanks for letting me know. I updated the code so it should work now. Also, I've added an [example page](http://greenstick.github.io/interactor/). Note that the example page is a work in progress, as is a more complete set of documentation for the methods. That said, for an idea of the parameters available for the configuration of Interactor, please checkout the initialization method of the JavaScript prototype in the file interactor.js. If you have any additional recommendations please let me know, and thanks!
