### ISSUE TITLE
Delegated event

### ISSUE THREAD

**Issue by xibman** [greenstick/interactor#5]
Hi,

i found a small problem with your lib when a dom element is created after dom ready.
It is impossible to track it so you need to crate a delegated event 

For exemple for the conversion capture:

```javascript
// Set Conversion Capture
        if (interactor.conversions === true) {
            for (var i = 0; i < interactor.conversionEvents.length; i++) {
                var ev      = interactor.conversionEvents[i];

                document.querySelector('body').addEventListener(ev, function (e) {
                    e.stopPropagation();
                    if(e.target.classList.contains(interactor.conversionElement)){
                        interactor.__addInteraction__(e, "conversion");
                    }
                });
            }
        }
```

**Comment by greenstick** [comment]
Thanks for the input, I'll run some tests and post an update in the near future – I'll leave this issue open until then. If you're so inclined, feel free to send a pull request : )

**Comment by xibman** [comment]
You can use the delegated event for both event (conversion & interaction)

**Comment by greenstick** [comment]
Update incoming.
