### ISSUE TITLE
I need an example on when the DOM changes after DOM ready

### ISSUE THREAD

**Issue by kpaool** [greenstick/interactor#6]
Hi,
So I'm trying to use the code but I have so many elements that load after DOM ready. And there previous issue didn't explain things well to me. Could you please show me how I could track for interations on DOM elements created after the initialisation

**Comment by greenstick** [comment]
Hey kpaool, apologies on the delayed response. I imagine you either figured it out or moved on to another solutions so I'm going to just comment and close this for the record. If you want to discuss it further, I can re-open the issue.

Interactor effectively assumes a static page load. At the time I wrote this, dynamic loading of elements existed but was far less common. While I don't plan to update the library to manage dynamic element loading, I imagine the simplest solution would be to load `Interactor` as you normally would (with a `<script src="interactor.min.js" type="application/javascript"></script>` tag in the `body`) and then have each `interactor` instance you need called when the dynamic content is loaded (i.e. just have the call to the interactor instance follow the HTML for the element that is dynamically injected). 

This is a very common challenge for a lot of libraries and there are a [number of approaches available](https://stackoverflow.com/questions/4057236/how-to-add-onload-event-to-a-div-element) (including ones within the library doing the dynamic loading).
